//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCenowy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanCenowy()
        {
            this.Abonament = new HashSet<Abonament>();
            this.PlanCenowyStawka = new HashSet<PlanCenowyStawka>();
        }
    
        public int PlanCenowyId { get; set; }
        public string Nazwa { get; set; }
        public string Waluta { get; set; }
        public string Opis { get; set; }
        public System.DateTime AktywnaOd { get; set; }
        public Nullable<System.DateTime> AktywnaDo { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonament> Abonament { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowyStawka> PlanCenowyStawka { get; set; }
    }
}
