//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownik()
        {
            this.Abonament = new HashSet<Abonament>();
            this.Abonament1 = new HashSet<Abonament>();
            this.Abonament2 = new HashSet<Abonament>();
            this.Klient = new HashSet<Klient>();
            this.Klient1 = new HashSet<Klient>();
            this.Klient2 = new HashSet<Klient>();
            this.PlanCenowy = new HashSet<PlanCenowy>();
            this.PlanCenowy1 = new HashSet<PlanCenowy>();
            this.PlanCenowy2 = new HashSet<PlanCenowy>();
            this.PlanCenowyStawka = new HashSet<PlanCenowyStawka>();
            this.PlanCenowyStawka1 = new HashSet<PlanCenowyStawka>();
            this.PlanCenowyStawka2 = new HashSet<PlanCenowyStawka>();
            this.Platnosc = new HashSet<Platnosc>();
            this.Platnosc1 = new HashSet<Platnosc>();
            this.Platnosc2 = new HashSet<Platnosc>();
            this.Rezerwacja = new HashSet<Rezerwacja>();
            this.Rezerwacja1 = new HashSet<Rezerwacja>();
            this.Rezerwacja2 = new HashSet<Rezerwacja>();
            this.Rower = new HashSet<Rower>();
            this.Rower1 = new HashSet<Rower>();
            this.Rower2 = new HashSet<Rower>();
            this.RowerModel = new HashSet<RowerModel>();
            this.RowerModel1 = new HashSet<RowerModel>();
            this.RowerModel2 = new HashSet<RowerModel>();
            this.Stacja = new HashSet<Stacja>();
            this.Stacja1 = new HashSet<Stacja>();
            this.Stacja2 = new HashSet<Stacja>();
            this.Stojak = new HashSet<Stojak>();
            this.Stojak1 = new HashSet<Stojak>();
            this.Stojak2 = new HashSet<Stojak>();
            this.TransferRoweru = new HashSet<TransferRoweru>();
            this.TransferRoweru1 = new HashSet<TransferRoweru>();
            this.TransferRoweru2 = new HashSet<TransferRoweru>();
            this.Wypozyczenie = new HashSet<Wypozyczenie>();
            this.Wypozyczenie1 = new HashSet<Wypozyczenie>();
            this.Wypozyczenie2 = new HashSet<Wypozyczenie>();
            this.WypozyczenieOplata = new HashSet<WypozyczenieOplata>();
            this.WypozyczenieOplata1 = new HashSet<WypozyczenieOplata>();
            this.WypozyczenieOplata2 = new HashSet<WypozyczenieOplata>();
            this.ZgloszenieSerwisowe = new HashSet<ZgloszenieSerwisowe>();
            this.ZgloszenieSerwisowe1 = new HashSet<ZgloszenieSerwisowe>();
            this.ZgloszenieSerwisowe2 = new HashSet<ZgloszenieSerwisowe>();
        }
    
        public int UzytkownikId { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Rola { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonament> Abonament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonament> Abonament1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonament> Abonament2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klient> Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klient> Klient1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klient> Klient2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowy> PlanCenowy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowy> PlanCenowy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowy> PlanCenowy2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowyStawka> PlanCenowyStawka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowyStawka> PlanCenowyStawka1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCenowyStawka> PlanCenowyStawka2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosc> Platnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosc> Platnosc1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosc> Platnosc2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rower> Rower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rower> Rower1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rower> Rower2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowerModel> RowerModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowerModel> RowerModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowerModel> RowerModel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stacja> Stacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stacja> Stacja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stacja> Stacja2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stojak> Stojak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stojak> Stojak1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stojak> Stojak2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRoweru> TransferRoweru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRoweru> TransferRoweru1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRoweru> TransferRoweru2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenie2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieOplata> WypozyczenieOplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieOplata> WypozyczenieOplata1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieOplata> WypozyczenieOplata2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZgloszenieSerwisowe> ZgloszenieSerwisowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZgloszenieSerwisowe> ZgloszenieSerwisowe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZgloszenieSerwisowe> ZgloszenieSerwisowe2 { get; set; }
    }
}
