//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikeRentalDbEntities : DbContext
    {
        public BikeRentalDbEntities()
            : base("name=BikeRentalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonament> Abonament { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<PlanCenowy> PlanCenowy { get; set; }
        public virtual DbSet<PlanCenowyStawka> PlanCenowyStawka { get; set; }
        public virtual DbSet<Platnosc> Platnosc { get; set; }
        public virtual DbSet<Rezerwacja> Rezerwacja { get; set; }
        public virtual DbSet<Rower> Rower { get; set; }
        public virtual DbSet<RowerModel> RowerModel { get; set; }
        public virtual DbSet<Stacja> Stacja { get; set; }
        public virtual DbSet<Stojak> Stojak { get; set; }
        public virtual DbSet<TransferRoweru> TransferRoweru { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenie { get; set; }
        public virtual DbSet<WypozyczenieOplata> WypozyczenieOplata { get; set; }
        public virtual DbSet<ZgloszenieSerwisowe> ZgloszenieSerwisowe { get; set; }
        public virtual DbSet<SlownikAbonamentStatus> SlownikAbonamentStatus { get; set; }
        public virtual DbSet<SlownikKlientTyp> SlownikKlientTyp { get; set; }
        public virtual DbSet<SlownikPlanCenowyStawkaTyp> SlownikPlanCenowyStawkaTyp { get; set; }
        public virtual DbSet<SlownikPlatnoscMetoda> SlownikPlatnoscMetoda { get; set; }
        public virtual DbSet<SlownikPlatnoscStatus> SlownikPlatnoscStatus { get; set; }
        public virtual DbSet<SlownikRezerwacjaStatus> SlownikRezerwacjaStatus { get; set; }
        public virtual DbSet<SlownikRowerStan> SlownikRowerStan { get; set; }
        public virtual DbSet<SlownikTransferStatus> SlownikTransferStatus { get; set; }
        public virtual DbSet<SlownikWypozyczenieOplataTyp> SlownikWypozyczenieOplataTyp { get; set; }
        public virtual DbSet<SlownikWypozyczenieStatus> SlownikWypozyczenieStatus { get; set; }
        public virtual DbSet<SlownikZgloszeniePriorytet> SlownikZgloszeniePriorytet { get; set; }
        public virtual DbSet<SlownikZgloszenieStatus> SlownikZgloszenieStatus { get; set; }
    }
}
