//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCenowyStawka
    {
        public int StawkaId { get; set; }
        public int PlanCenowyId { get; set; }
        public byte Typ { get; set; }
        public Nullable<int> OdMinuty { get; set; }
        public Nullable<int> DoMinuty { get; set; }
        public Nullable<decimal> CenaZaMin { get; set; }
        public Nullable<decimal> OplataStartowa { get; set; }
        public Nullable<int> LimitDarmowychMin { get; set; }
        public Nullable<decimal> DoplataPoLimicie { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        public virtual PlanCenowy PlanCenowy { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        public virtual SlownikPlanCenowyStawkaTyp SlownikPlanCenowyStawkaTyp { get; set; }
    }
}
