//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosc
    {
        public int PlatnoscId { get; set; }
        public int KlientId { get; set; }
        public Nullable<int> WypozyczenieId { get; set; }
        public System.DateTime DataPlatnosci { get; set; }
        public decimal Kwota { get; set; }
        public string Waluta { get; set; }
        public byte Metoda { get; set; }
        public string Referencja { get; set; }
        public byte Status { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        public virtual Wypozyczenie Wypozyczenie { get; set; }
    }
}
