//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        public int RezerwacjaId { get; set; }
        public int KlientId { get; set; }
        public int RowerId { get; set; }
        public System.DateTime DataOdUtc { get; set; }
        public System.DateTime DataDoUtc { get; set; }
        public byte Status { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Rower Rower { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        public virtual SlownikRezerwacjaStatus SlownikRezerwacjaStatus { get; set; }
    }
}
