//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rower()
        {
            this.Rezerwacja = new HashSet<Rezerwacja>();
            this.TransferRoweru = new HashSet<TransferRoweru>();
            this.Wypozyczenie = new HashSet<Wypozyczenie>();
            this.ZgloszenieSerwisowe = new HashSet<ZgloszenieSerwisowe>();
        }
    
        public int RowerId { get; set; }
        public int RowerModelId { get; set; }
        public string NumerSeryjny { get; set; }
        public string KodFloty { get; set; }
        public byte Stan { get; set; }
        public Nullable<int> OstatniaStacjaId { get; set; }
        public Nullable<int> OstatniStojakId { get; set; }
        public Nullable<decimal> OstatniaSzerGeo { get; set; }
        public Nullable<decimal> OstatniaDlugGeo { get; set; }
        public Nullable<decimal> PrzebiegKm { get; set; }
        public Nullable<byte> PoziomBateriiProc { get; set; }
        public Nullable<System.DateTime> DataPrzegladu { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        public virtual RowerModel RowerModel { get; set; }
        public virtual Stacja Stacja { get; set; }
        public virtual Stojak Stojak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRoweru> TransferRoweru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZgloszenieSerwisowe> ZgloszenieSerwisowe { get; set; }
    }
}
