//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlownikWypozyczenieOplataTyp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlownikWypozyczenieOplataTyp()
        {
            this.WypozyczenieOplata = new HashSet<WypozyczenieOplata>();
        }
    
        public byte TypId { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public int Kolejnosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieOplata> WypozyczenieOplata { get; set; }
    }
}
