//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stojak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stojak()
        {
            this.Rower = new HashSet<Rower>();
        }
    
        public int StojakId { get; set; }
        public int StacjaId { get; set; }
        public int NumerMiejsca { get; set; }
        public bool Sprawny { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rower> Rower { get; set; }
        public virtual Stacja Stacja { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
    }
}
