//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferRoweru
    {
        public int TransferId { get; set; }
        public int RowerId { get; set; }
        public int StacjaZrodlowaId { get; set; }
        public int StacjaDocelowaId { get; set; }
        public System.DateTime DataStartUtc { get; set; }
        public Nullable<System.DateTime> DataKoniecUtc { get; set; }
        public byte Status { get; set; }
        public string Uwagi { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        public virtual Rower Rower { get; set; }
        public virtual Stacja Stacja { get; set; }
        public virtual Stacja Stacja1 { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        public virtual SlownikTransferStatus SlownikTransferStatus { get; set; }
    }
}
