//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenie()
        {
            this.Platnosc = new HashSet<Platnosc>();
            this.WypozyczenieOplata = new HashSet<WypozyczenieOplata>();
        }
    
        public int WypozyczenieId { get; set; }
        public int KlientId { get; set; }
        public int RowerId { get; set; }
        public System.DateTime StartUtc { get; set; }
        public System.DateTime KoniecUtc { get; set; }
        public Nullable<int> StartStacjaId { get; set; }
        public Nullable<int> KoniecStacjaId { get; set; }
        public Nullable<decimal> StartSzerGeo { get; set; }
        public Nullable<decimal> StartDlugGeo { get; set; }
        public Nullable<decimal> KoniecSzerGeo { get; set; }
        public Nullable<decimal> KoniecDlugGeo { get; set; }
        public Nullable<decimal> OdlegloscKm { get; set; }
        public int PlanCenowyIdSnapshot { get; set; }
        public byte Status { get; set; }
        public bool CzyAktywny { get; set; }
        public int KtoDodal { get; set; }
        public System.DateTime KiedyDodal { get; set; }
        public Nullable<int> KtoModyfikowal { get; set; }
        public Nullable<System.DateTime> KiedyModyfikowal { get; set; }
        public Nullable<int> KtoWykasowal { get; set; }
        public Nullable<System.DateTime> KiedyWykasowal { get; set; }
    
        public virtual Klient Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosc> Platnosc { get; set; }
        public virtual Rower Rower { get; set; }
        public virtual Stacja Stacja { get; set; }
        public virtual Stacja Stacja1 { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
        public virtual Uzytkownik Uzytkownik2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieOplata> WypozyczenieOplata { get; set; }
        public virtual SlownikWypozyczenieStatus SlownikWypozyczenieStatus { get; set; }
    }
}
